### ISSUE TITLE
THANK YOU SO MUCH!

### ISSUE THREAD

**Issue by sayakpaul** [spellrun/spell-deeplab-voc-2012#4]
This is by far the simplest and most briefly comprehensive tutorial on DDP I have ever seen out there. You should consider sending a PR with this tutorial to the PyTorch repo. 

I was able to reuse the code snippets shared in the repository in my own project and I was able to get quite a neat speedup over `DataParallel`. [The accompanying blog post](https://spell.ml/blog/pytorch-distributed-data-parallel-XvEaABIAAB8Ars0e) also helped clarify many doubts. 

I have just one small doubt regarding the arguments of `DataLoader`:

Why aren't we specifying the `num_workers` argument? Also, when training on a GPU, `pin_memory=True` usually provides performance benefits. Did you play around with these two arguments? If so, do you mind sharing your findings?

Many thanks.

**Comment by ResidentMario** [comment]
Thank you for the kind words!

I didn't cover the optimizations you mentioned in this blog post, as I do not want to get stuck explaining what this optimization is and why it appears in the code. But I do discuss both it in [a different PyTorch performance-adjacent blog post](https://spell.ml/blog/pytorch-training-tricks-YAnJqBEAACkARhgD).

**Comment by sayakpaul** [comment]
Great stuff. Thanks once again.
